--- #YAML:1.0
name: Graphics-ColorNames
version: 0.39_02
author: Robert Rothenberg <rrwo at cpan.org>
abstract: defines RGB values for common color names
license: perl
requires:
  Carp: 0
  IO::File: 0
  perl: 5.6.0
build_requires:
  Test: 0
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.25
