---
name: Graphics-ColorNames
version: 2.01
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
abstract: defines RGB values for common color names
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  AutoLoader: 0
  Carp: 0
  DirHandle: 0
  Exporter: 0
  File::Spec: 0
  IO::File: 0
  Module::Load: 0.1
  base: 0
  perl: 5.6.0
build_requires:
  FileHandle: 0
  Test::More: 0
recommends:
  Test::Pod: 1
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
  Test::Prereq: 0
provides:
  Graphics::ColorNames:
    file: lib/Graphics/ColorNames.pm
    version: 2.01
  Graphics::ColorNames::HTML:
    file: lib/Graphics/ColorNames/HTML.pm
    version: 2.01
  Graphics::ColorNames::Netscape:
    file: lib/Graphics/ColorNames/Netscape.pm
    version: 2.01
  Graphics::ColorNames::Windows:
    file: lib/Graphics/ColorNames/Windows.pm
    version: 2.01
  Graphics::ColorNames::X:
    file: lib/Graphics/ColorNames/X.pm
    version: 2.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
